########################
###   AUTH-SERVICE   ###
########################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  replicas: 2
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: ejkej/snppd:auth-service
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 31000
  type: NodePort
---
########################
###   SNAP-SERVICE   ###
########################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snap-service
spec:
  selector:
    matchLabels:
      app: snap-service
  replicas: 2
  template:
    metadata:
      labels:
        app: snap-service
    spec:
      containers:
        - name: snap-service
          image: ejkej/snppd:snap-service
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: snap-service
spec:
  selector:
    app: snap-service
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30000
  type: NodePort
---
########################
###   USER-SERVICE   ###
########################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 2
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ejkej/snppd:user-service
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 32000
  type: NodePort